server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/snippets/nginx-locations.conf;
}

server {
    listen 443 ssl;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    include /etc/nginx/snippets/nginx-locations.conf;
}
